---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.0 comprend un certain nombre de nouvelles fonctionnalités et améliorations. 
---
= Nouveautés de Cloud Volumes ONTAP 9.10.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.0 comprend un certain nombre de nouvelles fonctionnalités et améliorations.

D'autres fonctionnalités et améliorations sont également introduites dans les dernières versions de BlueXP. Voir la https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notes de mise à jour BlueXP"^] pour plus d'informations.



== Les instances c4, m4 et r4 ne sont plus prises en charge (28 octobre 2022)

Dans AWS, les types d'instances EC2 c4, m4 et r4 ne sont plus pris en charge par Cloud Volumes ONTAP. Si un système existant s'exécute sur un type d'instance c4, m4 ou r4, vous devez passer à un type d'instance dans la famille d'instances c5, m5 ou r5.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Découvrez comment modifier le type d'instance EC2 pour Cloud Volumes ONTAP"^].

Reportez-vous à la section link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Support NetApp"^] pour en savoir plus sur la fin de disponibilité et la prise en charge de ces types d'instances.



== 9.10.0 GA (4 octobre 2021)

La version 9.10.0 GA est disponible pour AWS, Azure et Google Cloud. Cette version comprend de nouvelles fonctionnalités et améliorations suivantes.



=== Meilleures performances d'écriture

Nous avons amélioré les performances d'écriture Cloud Volumes ONTAP lorsque la vitesse d'écriture est élevée.



=== Augmentation de la taille des disques NVRAM dans Azure

La taille du disque NVRAM a été augmentée de 128 Gio à 512 Gio pour les nouveaux systèmes Cloud Volumes ONTAP dans Azure.


NOTE: Si vous choisissez un système à un seul nœud et que la machine virtuelle prend en charge des SSD Ultra, le système utilise un SSD Ultra de 32 Gio pour la mémoire NVRAM, plutôt qu'un SSD Premium de 512 Gio.



== Version requise du connecteur BlueXP

Le connecteur BlueXP doit exécuter la version 3.9.11 ou ultérieure pour déployer de nouveaux systèmes Cloud Volumes ONTAP 9.10.0 et mettre à niveau les systèmes existants vers la version 9.10.0.



== Notes de mise à niveau

* Les mises à niveau de Cloud Volumes ONTAP doivent être effectuées depuis BlueXP. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l'aide de System Manager ou de l'interface de ligne de commandes. Cela peut affecter la stabilité du système.
* Vous pouvez effectuer la mise à niveau vers Cloud Volumes ONTAP 9.10.0 à partir de la version 9.9.1. BlueXP vous invite à mettre à niveau vos systèmes Cloud Volumes ONTAP 9.9.1 existants vers la version 9.10.0.
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Découvrez comment effectuer la mise à niveau lorsque BlueXP vous avertit"^].

* La mise à niveau d'un système à un nœud unique permet de mettre le système hors ligne pendant 25 minutes au cours desquelles les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité s'effectue sans interruption et les E/S sont continues. Au cours de ce processus de mise à niveau sans interruption, chaque nœud est mis à niveau en tandem afin de continuer à traiter les E/S aux clients.




=== DS3_v2

Depuis la version 9.9.1, le type de machine virtuelle DS3_v2 n'est plus pris en charge avec les systèmes Cloud Volumes ONTAP nouveaux et existants. Si votre système est déjà exécuté sur ce type de machine virtuelle, vous devez changer de type de machine virtuelle avant de passer à la version 9.10.0.
